// <auto-generated />
using System;
using Exercicio_Semana9.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercicio_Semana9.Migrations
{
    [DbContext(typeof(SemanaContext))]
    partial class SemanaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercicio_Semana9.Models.SemanaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("AplicadoConteudo")
                        .HasColumnType("bit")
                        .HasColumnName("APLICADOCONTEUDO");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CONTEUDO");

                    b.Property<DateTime>("DataSemana")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA");

                    b.HasKey("id");

                    b.ToTable("Semana");
                });
#pragma warning restore 612, 618
        }
    }
}
